(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const app=$('#adminApp'),cfg=window.STUDYMATE_CONFIG||{};
  const hasSupabase=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase);
  const sb=hasSupabase?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
  const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36);
  const nowIso=()=>new Date().toISOString();
  const validUrl=u=>{try{const x=new URL(u);return ['http:','https:'].includes(x.protocol)}catch{return false}};
  const toast=(msg,type='')=>{const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;$('#toastRoot').appendChild(el);setTimeout(()=>el.remove(),3200)};
  const loading=()=>`<div class="loading"><div class="spinner"></div>جاري التحميل...</div>`;
  const local={read(k){try{return JSON.parse(localStorage.getItem('sm_'+k))||[]}catch{return []}},write(k,v){localStorage.setItem('sm_'+k,JSON.stringify(v))}};
  const db={
    async list(table){if(!hasSupabase)return local.read(table);const {data,error}=await sb.from(table).select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]},
    async insert(table,row){if(!hasSupabase){const a=local.read(table),n={id:uid(),...row,created_at:nowIso()};a.unshift(n);local.write(table,a);return n}const {data,error}=await sb.from(table).insert(row).select().single();if(error)throw error;return data},
    async update(table,id,row){if(!hasSupabase){const a=local.read(table).map(x=>String(x.id)===String(id)?{...x,...row}:x);local.write(table,a);return a.find(x=>String(x.id)===String(id))}const {data,error}=await sb.from(table).update(row).eq('id',id).select().single();if(error)throw error;return data},
    async remove(table,id){if(!hasSupabase){local.write(table,local.read(table).filter(x=>String(x.id)!==String(id)));return}const {error}=await sb.from(table).delete().eq('id',id);if(error)throw error}
  };
  const GRADES=['الكل','العاشر','الأول ثانوي','التوجيهي'];
  const SPECS=['الكل','تكنولوجيا المعلومات','إدارة الأعمال','الهندسة','التجميل','الزراعة','الضيافة','الفن والتصميم','البناء والإنشاءات','الإعلام الإبداعي','السياحة والسفر','الرعاية الصحية'];
  const TABS=[['overview','نظرة عامة'],['courses','الكورسات'],['lectures','المحاضرات'],['labs','اللابات'],['tasks','المهمات'],['resources','الملفات والروابط'],['quizzes','الكويزات'],['settings','الإعدادات']];
  let active='overview';

  const isLocalHost=['localhost','127.0.0.1','::1'].includes(location.hostname)||location.protocol==='file:';
  async function getAdminState(){
    if(!hasSupabase)return isLocalHost&&sessionStorage.getItem('sm_admin_local')==='1'?{local:true}:null;
    const {data:{user}}=await sb.auth.getUser();if(!user)return null;
    const {data:profile,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;
    if(profile?.role!=='admin')return {user,profile,denied:true};
    return {user,profile};
  }
  function login(){
    if(!hasSupabase&&!isLocalHost){app.innerHTML=`<div class="admin-login-wrap"><div class="admin-login-card"><span class="mini-label">STUDYMATE CONTROL</span><h1>لوحة الإدارة محمية</h1><p>تسجيل الدخول الإداري غير متاح على هذا النطاق بدون حساب إدارة موثّق.</p></div></div>`;return}
    app.innerHTML=`<div class="admin-login-wrap"><div class="admin-login-card"><span class="mini-label">STUDYMATE CONTROL</span><h1>دخول الإدارة</h1><p>${hasSupabase?'استخدم حساب الإدارة الخاص بك.':'أدخل رمز الإدارة للمتابعة.'}</p><div class="stack">${hasSupabase?`<div class="field"><label>البريد الإلكتروني</label><input id="aEmail" type="email" autocomplete="email"></div><div class="field"><label>كلمة المرور</label><input id="aPass" type="password" autocomplete="current-password"></div>`:`<div class="field"><label>رمز الإدارة</label><input id="aCode" type="password" autocomplete="off"></div>`}<button class="btn primary-blue" id="aLogin">دخول</button></div></div></div>`;
    $('#aLogin').onclick=async()=>{
      $('#aLogin').disabled=true;
      if(hasSupabase){const {error}=await sb.auth.signInWithPassword({email:$('#aEmail').value.trim(),password:$('#aPass').value});if(error){$('#aLogin').disabled=false;return toast('تعذر الدخول: '+error.message,'error')}const state=await getAdminState();if(!state||state.denied){await sb.auth.signOut();$('#aLogin').disabled=false;return toast('هذا الحساب لا يملك صلاحية الإدارة','error')}shell(state)}
      else{if(!isLocalHost||$('#aCode').value!==(cfg.LOCAL_ADMIN_CODE||'')){ $('#aLogin').disabled=false;return toast('رمز الإدارة غير صحيح','error')}sessionStorage.setItem('sm_admin_local','1');shell({local:true})}
    };
  }
  function shell(state){
    app.innerHTML=`<div class="admin-standalone"><div class="admin-top"><div><span class="mini-label">STUDYMATE CONTROL ROOM</span><h1>لوحة الإدارة</h1><p>${state.local?'إدارة الكورسات والمحاضرات واللابات والمهمات والملفات والكويزات.':safe(state.user?.email||'Admin')}</p></div><button class="btn secondary small" id="aLogout">تسجيل الخروج</button></div><div class="admin-tabs">${TABS.map(([id,label])=>`<button data-tab="${id}" class="${id===active?'active':''}">${label}</button>`).join('')}</div><section id="adminBody">${loading()}</section></div>`;
    $('#aLogout').onclick=async()=>{if(hasSupabase)await sb.auth.signOut();sessionStorage.removeItem('sm_admin_local');login()};
    $$('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===active));renderSection(active)});
    renderSection(active);
  }
  async function renderSection(type){const body=$('#adminBody');body.innerHTML=loading();try{if(type==='overview')return overview(body);if(type==='courses')return courses(body);if(type==='lectures')return lectures(body);if(type==='labs')return labs(body);if(type==='tasks')return tasks(body);if(type==='resources')return resources(body);if(type==='quizzes')return quizzes(body);if(type==='settings')return settings(body)}catch(e){console.error(e);body.innerHTML=`<div class="empty">حدث خطأ: ${safe(e.message||e)}</div>`}}

  async function overview(body){
    const [coursesA,lecturesA,labsA,tasksA,resourcesA,quizzesA]=await Promise.all(['courses','lectures','labs','tasks','resources','quizzes'].map(async t=>{try{return await db.list(t)}catch{return []}}));
    body.innerHTML=`<div class="overview-grid"><div class="metric"><b>${coursesA.length}</b><span>كورس</span></div><div class="metric"><b>${lecturesA.length}</b><span>محاضرة</span></div><div class="metric"><b>${labsA.length}</b><span>Lab</span></div><div class="metric"><b>${tasksA.length}</b><span>مهمة</span></div><div class="metric"><b>${resourcesA.length}</b><span>ملف/رابط</span></div><div class="metric"><b>${quizzesA.length}</b><span>كويز إضافي</span></div></div>`;
  }
  async function courses(body){
    const list=await db.list('courses');
    body.innerHTML=`<div class="two-col"><div class="admin-card"><h3 id="cFormTitle">إضافة كورس</h3><input id="cId" type="hidden"><div class="stack"><div class="field"><label>اسم الكورس *</label><input id="cTitle" maxlength="160"></div><div class="field"><label>الوصف</label><textarea id="cDesc" maxlength="1200"></textarea></div><div class="field"><label>رمز/أيقونة قصيرة</label><input id="cIcon" maxlength="8" placeholder="B"></div><label><input id="cPublished" type="checkbox" checked> منشور</label><div class="toolbar"><button class="btn" id="saveC">حفظ</button><button class="btn secondary hidden" id="cancelC">إلغاء</button></div></div></div><div class="admin-card"><h3>الكورسات</h3><div class="stack">${list.map(x=>rowActions(x,'c')).join('')||'<div class="empty">لا يوجد</div>'}</div></div></div>`;
    const reset=()=>{['cId','cTitle','cDesc','cIcon'].forEach(id=>$('#'+id).value='');$('#cPublished').checked=true;$('#cancelC').classList.add('hidden');$('#cFormTitle').textContent='إضافة كورس'};$('#cancelC').onclick=reset;
    $$('[data-edit-c]').forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.editC);$('#cId').value=x.id;$('#cTitle').value=x.title||'';$('#cDesc').value=x.description||'';$('#cIcon').value=x.icon||'';$('#cPublished').checked=x.is_published!==false;$('#cFormTitle').textContent='تعديل الكورس';$('#cancelC').classList.remove('hidden')});
    $('#saveC').onclick=async()=>{const title=$('#cTitle').value.trim();if(!title)return toast('اسم الكورس مطلوب','error');const row={title,description:$('#cDesc').value.trim(),icon:$('#cIcon').value.trim(),is_published:$('#cPublished').checked};try{$('#cId').value?await db.update('courses',$('#cId').value,row):await db.insert('courses',row);toast('تم حفظ الكورس');courses(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-c]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف الكورس؟ المحاضرات ستبقى لكن بدون ربط مباشر بالكورس.'))return;await db.remove('courses',b.dataset.delC);toast('تم الحذف');courses(body)});
  }
  function rowActions(x,prefix,extra=''){return `<div class="notice"><b>${safe(x.title||x.full_name||'بدون اسم')}</b>${extra}<div class="toolbar" style="float:left"><button class="btn secondary small" data-edit-${prefix}="${x.id}">تعديل</button><button class="btn danger small" data-del-${prefix}="${x.id}">حذف</button></div></div>`}
  async function lectures(body){
    const [list,courseRows]=await Promise.all([db.list('lectures'),db.list('courses')]);
    body.innerHTML=`<div class="two-col"><div class="admin-card"><h3 id="lFormTitle">إضافة محاضرة</h3><input id="lId" type="hidden"><div class="stack"><div class="field"><label>العنوان *</label><input id="lTitle"></div><div class="field"><label>الكورس</label><select id="lCourse"><option value="">بدون</option>${courseRows.map(c=>`<option value="${c.id}">${safe(c.title)}</option>`).join('')}</select></div><div class="field"><label>الوحدة</label><input id="lUnit"></div><div class="field"><label>الشرح</label><textarea id="lDesc"></textarea></div><div class="field"><label>رابط YouTube</label><input id="lYoutube" type="url"></div><label><input id="lPublished" type="checkbox" checked> منشور</label><div class="toolbar"><button class="btn" id="saveL">حفظ</button><button class="btn secondary hidden" id="cancelL">إلغاء</button></div></div></div><div class="admin-card"><h3>المحاضرات</h3><div class="stack">${list.map(x=>rowActions(x,'l',`<span class="small-muted"> — ${safe(courseRows.find(c=>String(c.id)===String(x.course_id))?.title||x.course||'بدون كورس')}</span>`)).join('')||'<div class="empty">لا يوجد</div>'}</div></div></div>`;
    const reset=()=>{['lId','lTitle','lUnit','lDesc','lYoutube'].forEach(id=>$('#'+id).value='');$('#lCourse').value='';$('#lPublished').checked=true;$('#cancelL').classList.add('hidden');$('#lFormTitle').textContent='إضافة محاضرة'};$('#cancelL').onclick=reset;
    $$('[data-edit-l]').forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.editL);$('#lId').value=x.id;$('#lTitle').value=x.title||'';$('#lCourse').value=x.course_id||'';$('#lUnit').value=x.unit||'';$('#lDesc').value=x.description||'';$('#lYoutube').value=x.youtube_url||'';$('#lPublished').checked=x.is_published!==false;$('#lFormTitle').textContent='تعديل المحاضرة';$('#cancelL').classList.remove('hidden')});
    $('#saveL').onclick=async()=>{const title=$('#lTitle').value.trim(),youtube_url=$('#lYoutube').value.trim();if(!title)return toast('العنوان مطلوب','error');if(youtube_url&&!validUrl(youtube_url))return toast('رابط YouTube غير صحيح','error');const c=courseRows.find(c=>String(c.id)===$('#lCourse').value);const row={title,course_id:$('#lCourse').value||null,course:c?.title||'',unit:$('#lUnit').value.trim(),description:$('#lDesc').value.trim(),youtube_url,is_published:$('#lPublished').checked};try{$('#lId').value?await db.update('lectures',$('#lId').value,row):await db.insert('lectures',row);toast('تم الحفظ');lectures(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-l]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف المحاضرة؟'))return;await db.remove('lectures',b.dataset.delL);toast('تم الحذف');lectures(body)});
  }
  async function labs(body){
    const [list,lecs]=await Promise.all([db.list('labs'),db.list('lectures')]);
    body.innerHTML=`<div class="two-col"><div class="admin-card"><h3 id="labFormTitle">إضافة Lab</h3><input id="labId" type="hidden"><div class="stack"><div class="field"><label>الاسم *</label><input id="labTitle"></div><div class="field"><label>المحاضرة</label><select id="labLecture"><option value="">بدون</option>${lecs.map(l=>`<option value="${l.id}">${safe(l.title)}</option>`).join('')}</select></div><div class="field"><label>الوصف</label><textarea id="labDesc"></textarea></div><div class="field"><label>التعليمات</label><textarea id="labInst"></textarea></div><div class="field"><label>رابط اللاب</label><input id="labUrl" type="url"></div><label><input id="labPublished" type="checkbox" checked> منشور</label><div class="toolbar"><button class="btn" id="saveLab">حفظ</button><button class="btn secondary hidden" id="cancelLab">إلغاء</button></div></div></div><div class="admin-card"><h3>اللابات</h3><div class="stack">${list.map(x=>rowActions(x,'lab')).join('')||'<div class="empty">لا يوجد</div>'}</div></div></div>`;
    const reset=()=>{['labId','labTitle','labDesc','labInst','labUrl'].forEach(id=>$('#'+id).value='');$('#labLecture').value='';$('#labPublished').checked=true;$('#cancelLab').classList.add('hidden');$('#labFormTitle').textContent='إضافة Lab'};$('#cancelLab').onclick=reset;
    $$('[data-edit-lab]').forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.editLab);$('#labId').value=x.id;$('#labTitle').value=x.title||'';$('#labLecture').value=x.lecture_id||'';$('#labDesc').value=x.description||'';$('#labInst').value=x.instructions||'';$('#labUrl').value=x.lab_url||'';$('#labPublished').checked=x.is_published!==false;$('#labFormTitle').textContent='تعديل Lab';$('#cancelLab').classList.remove('hidden')});
    $('#saveLab').onclick=async()=>{const title=$('#labTitle').value.trim(),lab_url=$('#labUrl').value.trim();if(!title)return toast('اسم اللاب مطلوب','error');if(lab_url&&!validUrl(lab_url))return toast('الرابط غير صحيح','error');const row={title,lecture_id:$('#labLecture').value||null,description:$('#labDesc').value.trim(),instructions:$('#labInst').value.trim(),lab_url,is_published:$('#labPublished').checked};try{$('#labId').value?await db.update('labs',$('#labId').value,row):await db.insert('labs',row);toast('تم الحفظ');labs(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-lab]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف اللاب؟'))return;await db.remove('labs',b.dataset.delLab);toast('تم الحذف');labs(body)});
  }
  async function resources(body){
    const list=await db.list('resources');
    body.innerHTML=`<div class="two-col"><div class="admin-card"><h3 id="rFormTitle">إضافة ملف / رابط</h3><input id="rId" type="hidden"><div class="stack"><div class="field"><label>العنوان *</label><input id="rTitle"></div><div class="field"><label>الوصف</label><textarea id="rDesc"></textarea></div><div class="field"><label>الرابط *</label><input id="rUrl" type="url" placeholder="https://..."></div><div class="field"><label>النوع</label><select id="rKind"><option>رابط</option><option>ملف</option><option>ملخص</option><option>نموذج</option></select></div><div class="field"><label>الصف</label><select id="rGrade">${GRADES.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>التخصص</label><select id="rSpec">${SPECS.map(x=>`<option>${x}</option>`).join('')}</select></div><label><input id="rPublished" type="checkbox" checked> منشور</label><div class="toolbar"><button class="btn" id="saveR">حفظ</button><button class="btn secondary hidden" id="cancelR">إلغاء</button></div></div></div><div class="admin-card"><h3>الملفات والروابط</h3><div class="stack">${list.map(x=>rowActions(x,'r',`<span class="small-muted"> — ${safe(x.grade||'الكل')} / ${safe(x.specialization||'الكل')}</span>`)).join('')||'<div class="empty">لا يوجد</div>'}</div></div></div>`;
    const reset=()=>{['rId','rTitle','rDesc','rUrl'].forEach(id=>$('#'+id).value='');$('#rKind').value='رابط';$('#rGrade').value='الكل';$('#rSpec').value='الكل';$('#rPublished').checked=true;$('#cancelR').classList.add('hidden');$('#rFormTitle').textContent='إضافة ملف / رابط'};$('#cancelR').onclick=reset;
    $$('[data-edit-r]').forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.editR);$('#rId').value=x.id;$('#rTitle').value=x.title||'';$('#rDesc').value=x.description||'';$('#rUrl').value=x.url||'';$('#rKind').value=x.kind||'رابط';$('#rGrade').value=x.grade||'الكل';$('#rSpec').value=x.specialization||'الكل';$('#rPublished').checked=x.is_published!==false;$('#rFormTitle').textContent='تعديل الملف / الرابط';$('#cancelR').classList.remove('hidden')});
    $('#saveR').onclick=async()=>{const title=$('#rTitle').value.trim(),url=$('#rUrl').value.trim();if(!title)return toast('العنوان مطلوب','error');if(!validUrl(url))return toast('الرابط غير صحيح','error');const row={title,description:$('#rDesc').value.trim(),url,kind:$('#rKind').value,grade:$('#rGrade').value,specialization:$('#rSpec').value,is_published:$('#rPublished').checked};try{$('#rId').value?await db.update('resources',$('#rId').value,row):await db.insert('resources',row);toast('تم الحفظ');resources(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-r]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف هذا العنصر؟'))return;await db.remove('resources',b.dataset.delR);toast('تم الحذف');resources(body)});
  }
  async function tasks(body){
    const list=await db.list('tasks');
    body.innerHTML=`<div class="two-col"><div class="admin-card"><h3 id="tFormTitle">إضافة مهمة</h3><input id="tId" type="hidden"><div class="stack">
      <div class="field"><label>عنوان المهمة *</label><input id="tTitle" maxlength="180"></div>
      <div class="field"><label>وصف المهمة</label><textarea id="tDesc" maxlength="2500"></textarea></div>
      <div class="field"><label>رابط/ملف المهمة</label><input id="tUrl" type="url" placeholder="https://..."></div>
      <div class="field"><label>شرح المهمة</label><textarea id="tExplain" maxlength="3500"></textarea></div>
      <div class="field"><label>رابط/ملف شرح المهمة</label><input id="tExplainUrl" type="url" placeholder="https://..."></div>
      <div class="field"><label>الصف</label><select id="tGrade">${GRADES.map(x=>`<option>${x}</option>`).join('')}</select></div>
      <div class="field"><label>التخصص</label><select id="tSpec">${SPECS.map(x=>`<option>${x}</option>`).join('')}</select></div>
      <label><input id="tPublished" type="checkbox" checked> منشور</label>
      <div class="toolbar"><button class="btn" id="saveT">حفظ</button><button class="btn secondary hidden" id="cancelT">إلغاء</button></div>
    </div></div><div class="admin-card"><h3>المهمات</h3><div class="stack">${list.map(x=>rowActions(x,'t',`<span class="small-muted"> — ${safe(x.grade||'الكل')} / ${safe(x.specialization||'الكل')}</span>`)).join('')||'<div class="empty">لا توجد مهمات بعد.</div>'}</div></div></div>`;
    const reset=()=>{['tId','tTitle','tDesc','tUrl','tExplain','tExplainUrl'].forEach(id=>$('#'+id).value='');$('#tGrade').value='الكل';$('#tSpec').value='الكل';$('#tPublished').checked=true;$('#cancelT').classList.add('hidden');$('#tFormTitle').textContent='إضافة مهمة'};$('#cancelT').onclick=reset;
    $$('[data-edit-t]').forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.editT);$('#tId').value=x.id;$('#tTitle').value=x.title||'';$('#tDesc').value=x.description||'';$('#tUrl').value=x.task_url||'';$('#tExplain').value=x.explanation||'';$('#tExplainUrl').value=x.explanation_url||'';$('#tGrade').value=x.grade||'الكل';$('#tSpec').value=x.specialization||'الكل';$('#tPublished').checked=x.is_published!==false;$('#tFormTitle').textContent='تعديل المهمة';$('#cancelT').classList.remove('hidden')});
    $('#saveT').onclick=async()=>{const title=$('#tTitle').value.trim(),task_url=$('#tUrl').value.trim(),explanation_url=$('#tExplainUrl').value.trim();if(!title)return toast('عنوان المهمة مطلوب','error');if(task_url&&!validUrl(task_url))return toast('رابط المهمة غير صحيح','error');if(explanation_url&&!validUrl(explanation_url))return toast('رابط الشرح غير صحيح','error');const row={title,description:$('#tDesc').value.trim(),task_url,explanation:$('#tExplain').value.trim(),explanation_url,grade:$('#tGrade').value,specialization:$('#tSpec').value,is_published:$('#tPublished').checked};try{$('#tId').value?await db.update('tasks',$('#tId').value,row):await db.insert('tasks',row);toast('تم حفظ المهمة');tasks(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-t]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف المهمة؟'))return;await db.remove('tasks',b.dataset.delT);toast('تم الحذف');tasks(body)});
  }

  async function settings(body){
    const list=await db.list('site_settings').catch(()=>[]);
    const current=list.find(x=>String(x.id)==='main')||list[0]||{};
    body.innerHTML=`<div class="admin-card" style="max-width:760px"><h3>إعدادات التواصل</h3><p>ضع رقم واتساب بصيغة دولية بدون +، مثال: 9627XXXXXXXX.</p><div class="stack"><div class="field"><label>رقم واتساب للفيدباك</label><input id="waNumber" inputmode="tel" value="${safe(current.whatsapp_number||'')}" placeholder="9627XXXXXXXX"></div><button class="btn" id="saveSettings">حفظ الإعدادات</button></div></div>`;
    $('#saveSettings').onclick=async()=>{const whatsapp_number=$('#waNumber').value.replace(/\D/g,'');if(whatsapp_number&&whatsapp_number.length<10)return toast('رقم واتساب غير صحيح','error');try{if(current.id)await db.update('site_settings',current.id,{whatsapp_number});else await db.insert('site_settings',{id:'main',whatsapp_number});toast('تم حفظ رقم واتساب')}catch(e){toast(e.message,'error')}};
  }

  async function quizzes(body){
    const list=await db.list('quizzes');body.innerHTML=`<div class="two-col"><div class="admin-card"><h3>إضافة كويز</h3><div class="stack"><div class="field"><label>العنوان *</label><input id="qTitle"></div><div class="field"><label>التصنيف</label><input id="qCategory"></div><div class="field"><label>الأسئلة JSON</label><textarea id="qJson" style="min-height:260px" placeholder='[{"question":"السؤال؟","options":["أ","ب"],"answer":"ب"}]'></textarea></div><label><input id="qPublished" type="checkbox" checked> منشور</label><button class="btn" id="saveQ">إضافة</button></div></div><div class="admin-card"><h3>الكويزات المضافة</h3><div class="stack">${list.map(x=>`<div class="notice"><b>${safe(x.title)}</b> — ${(x.payload?.questions||[]).length} سؤال <button class="btn danger small" data-del-q="${x.id}" style="float:left">حذف</button></div>`).join('')||'<div class="empty">لا يوجد</div>'}</div></div></div>`;
    $('#saveQ').onclick=async()=>{const title=$('#qTitle').value.trim();if(!title)return toast('العنوان مطلوب','error');let questions;try{questions=JSON.parse($('#qJson').value);if(!Array.isArray(questions)||!questions.length)throw 0}catch{return toast('JSON غير صحيح','error')}try{await db.insert('quizzes',{title,category:$('#qCategory').value.trim(),payload:{questions},is_published:$('#qPublished').checked});toast('تمت الإضافة');quizzes(body)}catch(e){toast(e.message,'error')}};
    $$('[data-del-q]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف الكويز؟'))return;await db.remove('quizzes',b.dataset.delQ);toast('تم الحذف');quizzes(body)});
  }
  async function students(body){
    let list=[];if(hasSupabase)list=(await db.list('profiles')).filter(x=>x.role!=='admin');else list=local.read('students');
    body.innerHTML=`<div class="admin-card"><h3>الطلاب</h3><div class="admin-list-scroll"><table class="admin-table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>تاريخ التسجيل</th></tr></thead><tbody>${list.map(x=>`<tr><td>${safe(x.full_name||[x.first_name,x.last_name].filter(Boolean).join(' '))}</td><td dir="ltr">${safe(x.phone||'—')}</td><td>${safe((x.created_at||'').slice(0,10)||'—')}</td></tr>`).join('')||'<tr><td colspan="3">لا يوجد طلاب بعد.</td></tr>'}</tbody></table></div></div>`;
  }
  async function progress(body){
    const list=await db.list('lecture_progress'),lecs=await db.list('lectures');let studentsA=[];if(hasSupabase)studentsA=await db.list('profiles');else studentsA=local.read('students');
    const studentName=k=>{const s=studentsA.find(x=>String(x.id||x.phone)===String(k));return s?.full_name||[s?.first_name,s?.last_name].filter(Boolean).join(' ')||k||'طالب'};
    body.innerHTML=`<div class="admin-card"><h3>تقدم الطلاب بالمحاضرات</h3><div class="admin-list-scroll"><table class="admin-table"><thead><tr><th>الطالب</th><th>المحاضرة</th><th>الحالة</th><th>آخر فتح</th></tr></thead><tbody>${list.map(x=>`<tr><td>${safe(studentName(x.user_id||x.student_key))}</td><td>${safe(lecs.find(l=>String(l.id)===String(x.lecture_id))?.title||x.lecture_id)}</td><td>${x.completed?'✓ مكتملة':'قيد الدراسة'}</td><td>${safe((x.last_opened_at||'').replace('T',' ').slice(0,16))}</td></tr>`).join('')||'<tr><td colspan="4">لا يوجد تقدم مسجل بعد.</td></tr>'}</tbody></table></div></div>`;
  }
  async function attempts(body){
    const list=await db.list('quiz_attempts');let studentsA=[];if(hasSupabase)studentsA=await db.list('profiles');else studentsA=local.read('students');
    const studentName=k=>{const s=studentsA.find(x=>String(x.id||x.phone)===String(k));return s?.full_name||[s?.first_name,s?.last_name].filter(Boolean).join(' ')||k||'طالب'};
    body.innerHTML=`<div class="admin-card"><h3>نتائج الكويزات</h3><div class="admin-list-scroll"><table class="admin-table"><thead><tr><th>الطالب</th><th>الكويز</th><th>النتيجة</th><th>التاريخ</th></tr></thead><tbody>${list.map(x=>`<tr><td>${safe(studentName(x.user_id||x.student_key))}</td><td>${safe(x.quiz_title||x.quiz_key||'كويز')}</td><td><b style="color:#8dc4ff">${Number(x.percentage ?? (x.total?Math.round(Number(x.score||0)/Number(x.total)*100):0))}%</b> <small>(${Number(x.score||0)}/${Number(x.total||0)})</small></td><td>${safe(String(x.created_at||'').replace('T',' ').slice(0,16))}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد نتائج بعد.</td></tr>'}</tbody></table></div></div>`;
  }
  async function submissions(body){
    const [list,labsA]=await Promise.all([db.list('lab_submissions'),db.list('labs')]);let studentsA=[];if(hasSupabase)studentsA=await db.list('profiles');else studentsA=local.read('students');const sName=k=>{const s=studentsA.find(x=>String(x.id||x.phone)===String(k));return s?.full_name||[s?.first_name,s?.last_name].filter(Boolean).join(' ')||k||'طالب'};
    body.innerHTML=`<div class="admin-card"><h3>تسليمات اللابات</h3><div class="admin-list-scroll"><table class="admin-table"><thead><tr><th>الطالب</th><th>اللاب</th><th>التسليم</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${list.map(x=>`<tr><td>${safe(sName(x.user_id||x.student_key))}</td><td>${safe(labsA.find(l=>String(l.id)===String(x.lab_id))?.title||x.lab_id)}</td><td>${x.submission_url||x.url?`<a href="${safe(x.submission_url||x.url)}" target="_blank">رابط</a>`:''} ${x.file_path&&hasSupabase?`<button class="btn secondary small" data-open-file="${safe(x.file_path)}">فتح الملف</button>`:safe(x.file_name||x.file_path||'')}<br><small>${safe(x.note||'')}</small></td><td><span class="status-pill ${safe(x.status||'pending')}">${x.status==='done'?'مقبول':x.status==='rejected'?'مرفوض':'قيد المراجعة'}</span>${x.feedback?`<br><small>${safe(x.feedback)}</small>`:''}</td><td><button class="btn secondary small" data-review="${x.id}">مراجعة</button></td></tr>`).join('')||'<tr><td colspan="5">لا توجد تسليمات بعد.</td></tr>'}</tbody></table></div></div>`;
    $$('[data-open-file]').forEach(b=>b.onclick=async()=>{try{const {data,error}=await sb.storage.from('submissions').createSignedUrl(b.dataset.openFile,600);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}catch(e){toast('تعذر فتح الملف: '+e.message,'error')}});
    $$('[data-review]').forEach(b=>b.onclick=async()=>{const x=list.find(v=>String(v.id)===b.dataset.review);const status=prompt('اكتب الحالة: pending أو done أو rejected',x.status||'pending');if(!['pending','done','rejected'].includes(status||''))return;const feedback=prompt('ملاحظة للطالب (اختياري)',x.feedback||'')||'';try{await db.update('lab_submissions',x.id,{status,feedback});toast('تم تحديث التسليم');submissions(body)}catch(e){toast(e.message,'error')}});
  }

  async function init(){try{const state=await getAdminState();if(state?.denied){await sb.auth.signOut();return login()}state?shell(state):login()}catch(e){console.error(e);login()}}
  init();
})();
